### ISSUE TITLE
Slow installation process

### ISSUE THREAD

**Issue by rblanchot** [MefhigosetH/pinguino-nsi-installer#19]
IMO, the main problem remains the installation duration : about half-an-hour @115kB/s this morning on my "blank" (without anything : no python, no beautifulsoup, etc ...) windows XP laptop. Would it be possible to ask user which compiler (sdcc-mpic16 for 8-bit, gcc-mips-elf for 32-bit or both) he wants, in order to speed up the installation process ?

**Comment by MefhigosetH** [comment]
Yes, no problem. It's an excellent idea. All I need is that the installer is able to download any of the two versions (8 or 32 bits) of pinguino-compilers separately. Could we have a separate zip file for each of these architectures, for Windows? I plan add a intermediate page (screen) in the Installer, from the user can select what component want install in your system.

**Comment by MefhigosetH** [comment]
Implemented on v1.1.0-beta3 release.
