### ISSUE TITLE
Pinguino IDE icon

### ISSUE THREAD

**Issue by rblanchot** [MefhigosetH/pinguino-nsi-installer#20]
Wrong Pinguino IDE icon (python's icon), I used this file for Linux :
![Uploading logo.png . . .]()

**Comment by rblanchot** [comment]
![logo](https://f.cloud.github.com/assets/5788750/2273111/11263954-9f0c-11e3-84f9-52a07cba9511.png)

**Comment by MefhigosetH** [comment]
Ok, thanks!

**Comment by MefhigosetH** [comment]
Fixed.
