### ISSUE TITLE
Device Not Found [Pinguino Project]

### ISSUE THREAD

**Issue by ajsb85** [MefhigosetH/pinguino-nsi-installer#38]
I have this board:
USB\VID_04D8&PID_FEAA&REV_0100
I can see the device in the device manager as the name: Pinguino Project
But not apear.

Spanish:
No aparece mi dispositivo en la lista.

![capture2](https://cloud.githubusercontent.com/assets/663460/6011516/c26a9d40-ab0e-11e4-9673-4b747a11d829.PNG)

![capture](https://cloud.githubusercontent.com/assets/663460/6011494/98d333c0-ab0e-11e4-909b-e9e7755c95ce.PNG)

![capture3](https://cloud.githubusercontent.com/assets/663460/6011496/98df7d92-ab0e-11e4-8da1-d48ea6131a7e.PNG)

**Comment by MefhigosetH** [comment]
Hola Alex,

El filtro de LibUSB muestra en su lista, sólo aquellos dispositivos que no están gobernados por esta librería. Si el PIC no aparece, quizás los drivers para éste, ya lo hayan configurado. No significa mucho que no aparezca.

Lo importante es que figure en el Administrador de Dispositivos. Sólo que en tu caso aparece con un signo de admiración amarillo. Por favor, haz clic derecho sobre el dispositivo Pinguino Project y seleccione propiedades. Adjunta un Screenshot para ver que dice esa pantalla.

Por cierto, dime que S.O. utilizas y si es de 32 o 64 bits.

Gracias!

**Comment by ajsb85** [comment]
Tengo Windows 8.1 Update 1.
Hya otro error que no reconoce el directorio de python en uno de los instaladores pero olvidé tomar una captura de pantalla.

![capture4](https://cloud.githubusercontent.com/assets/663460/6012030/d07c74b6-ab14-11e4-8f3f-99912429d7e5.PNG)

**Comment by MefhigosetH** [comment]
Ok, Los driver no se habrán instalado correctamente.

Por favor, clic en Update Driver y cuando pregunte, dile al Windows que busque en la carpeta C:\pinguino-11\drivers. No recuerdo en este momento, pero creo que hay una carpeta para Windows 7 que también sirve para 8. Si te advierte que los drivers no están firmados, dile que si.

Por problemas con controladores no firmados, visita el siguiente tutorial:
http://josmangarsal.es/instalar-drivers-no-firmados-en-windows-8-y-8-1/

**Comment by ajsb85** [comment]
En Windows 8 y 8.1 si los drivers no estan firmados no los instala, tengo que entrar en modo de arranque avanzado para deshabilitar la opción de drivers firmados
![capture5](https://cloud.githubusercontent.com/assets/663460/6012094/da2973a0-ab15-11e4-8157-7ba8ceb091c3.PNG)

**Comment by MefhigosetH** [comment]
Y arrancando en modo avanzado y dehabilitando el uso obligatorio de controladores firmados, te permitió instalar el dispositivo ?

**Comment by ajsb85** [comment]
Si, no he reiniciado, no he probado, pero ya lo he hecho con otros dispositivos y funciona,
El modo avanzado lo puedes ejecutar via nsis también.
Pero yo sugeriria firmar los drivers, hay empresas que regalan certificados para firmar hardware cuando son proyectos de software libre o hardware libre.

**Comment by MefhigosetH** [comment]
Muchas gracias por tu feedback.

Agradecería compartas cualquier información sobre firmar los drivers, dado que desconocía totalmente lo que comentas. Puedes ponerte en contacto con @rblanchot que es el coordinador de este proyecto. Sería interesantísimo poder firmar los controladores de forma gratuita, dada nuestra filosofía OpenHardware.

Sobre ejecutarlo via NSIS, me informaré debidamente. Agradezco tus sugerencias.

**Comment by ajsb85** [comment]
Excelente, voy primero a firmar los controladores por mi cuenta para poderles dar un mejor soporte a ustedes. Yo tengo un certificado. 

Una propuesta a largo plazo es:
- NSIS está ya descontinuado, aunque funciona, yo te sugiero ir aprendiendo en la marcha sobre "WiX Toolset"
- Otra sugerencia es crear tu mismo los instaladores de cada aplicación de terceros que se instala. El código fuente de esos instaladores se consiguen.

Saludos desde Venezuela.
Un abrazo.
